# Generated by Django 3.0.7 on 2020-07-04 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('timeCreation', models.DateTimeField(auto_now_add=True)),
                ('lastSeenTime', models.DateTimeField(auto_now=True)),
                ('emailkey', models.TextField()),
                ('emailauth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=15)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('photo', models.ImageField(default='profilePhotos/default.jpg', upload_to='profilePhotos/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messDel.user')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messDel.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='messDel.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='messDel.user')),
            ],
        ),
    ]
