# Generated by Django 3.0.7 on 2020-07-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messDel', '0002_auto_20200704_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='photo',
            field=models.ImageField(default='profilePhotos/default.jpg', null=True, upload_to='profilePhotos/'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='status',
            field=models.CharField(default='Available', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
