# Generated by Django 3.0.7 on 2020-06-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messDel', '0002_auto_20200621_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='time_Creation',
        ),
        migrations.AddField(
            model_name='user',
            name='lastSeenTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
