# Generated by Django 3.0.7 on 2020-06-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messDel', '0003_auto_20200621_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_Creation',
            new_name='timeCreation',
        ),
    ]
